project1/project1/urls.py
from django.contrib import admin
from django.urls import path
from blackbelt.views import (
    LoginView,
    MainView,
    GroupAddView,
    GroupsView,
    StudentsView,
    StudentAddView,
    StudentEditView,
    LogoutView,
    GroupEditView,
    StudentDetailsView,
    GroupDetailsView,
    PresenceView,
    StudentDeleteView,
    GroupDeleteView,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("login/", LoginView.as_view(), name="login"),
    path("main/", MainView.as_view(), name="main"),
    path("group_add/", GroupAddView.as_view(), name="group-add"),
    path("groups/", GroupsView.as_view(), name="groups"),
    path("students/", StudentsView.as_view(), name="students"),
    path("student_add/", StudentAddView.as_view(), name="student-add"),
    path("student_edit/<pk>", StudentEditView.as_view(), name="student-edit"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("group_edit/<pk>", GroupEditView.as_view(), name="group-edit"),
    path(
        "student_details/<int:student_id>",
        StudentDetailsView.as_view(),
        name="student-details",
    ),
    path(
        "group_details/<int:group_id>", GroupDetailsView.as_view(), name="group-details"
    ),
    path("presence/", PresenceView.as_view(), name="presence"),
    path("student_edit/<pk>", StudentEditView.as_view(), name="student-edit"),
    path("student_delete/<pk>", StudentDeleteView.as_view(), name="student-delete"),
    path("group_delete/<pk>", GroupDeleteView.as_view(), name="group-delete"),
]

project1/blackbelt/models.py
from django.db import models

BELT_SYSTEM = (
    (1, "BIAŁY"),
    (2, "BIAŁY 1"),
    (3, "BIAŁY 2"),
    (4, "BIAŁY 3"),
    (5, "BIAŁY 4"),
    (6, "NIEBIECKI"),
    (7, "NIEBIESKI 1"),
    (8, "NIEBIESKI 2"),
    (9, "NIEBIESKI 3"),
    (10, "NIEBIESKI 4"),
    (11, "PURPUROWY"),
    (12, "PURPUROWY 1"),
    (13, "PURPUROWY 2"),
    (14, "PURPUROWY 3"),
    (15, "PURPUROWY 4"),
    (16, "BRĄZOWY"),
    (17, "BRĄZOWY 1"),
    (18, "BRĄZOWY 2"),
    (19, "BRĄZOWY 3"),
    (20, "BRĄZOWY 4"),
    (21, "CZARNY"),
)


class Group(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name="Nazwa grupy")
    trainer = models.CharField(max_length=64, verbose_name="Trener")

    def __str__(self):
        return self.name


class Student(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name="Imię i nazwisko")
    phone = models.IntegerField(verbose_name="Telefon")
    email = models.EmailField(verbose_name="e-mail")
    groups = models.ManyToManyField(Group)
    notes = models.TextField(verbose_name="Adnotacje")
    belt = models.IntegerField(
        choices=BELT_SYSTEM, default=1, max_length=64, verbose_name="Pas"
    )

    def __str__(self):
        return self.name


# class StudentBelt(models.Model):
#     belt = models.CharField(
#         choices=BELT_SYSTEM, default=1, max_length=64, verbose_name="Pas"
#     )
#     student = models.ForeignKey(Student, on_delete=models.CASCADE)
#     promotion_date = models.DateTimeField(auto_now=True, verbose_name="Data otrzymania")


class PresenceList(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, verbose_name="Uczeń")
    day = models.DateField(verbose_name="Data")
    present = models.BooleanField(null=True, verbose_name="obecny")


class Payments(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    month = models.DateField(verbose_name="Miesiąc")

project1/blackbelt/forms.py
from django import forms
from django.forms import ModelForm
from .models import Group, Student, PresenceList, Payments


class LoginForm(forms.Form):
    username = forms.CharField(label="Login:")
    password = forms.CharField(label="Hasło:", widget=forms.PasswordInput)


class PresenceForm(forms.Form):
    student = forms.ModelChoiceField(
        queryset=Student.objects.all(),
        label="Uczeń",
        # widget=forms.CheckboxSelectMultiple,
    )
    day = forms.DateField(label="Data", widget=forms.SelectDateWidget)
    present = forms.BooleanField(label="Obecny?", required=False)


# class PresenceForm(ModelForm):
#     class Meta:
#         model = PresenceList
#         fields = "__all__"


# class PaymentForm(forms.Form):
#     student = forms.ModelChoiceField(
#         queryset=Student.objects.all(),
#         label="Uczeń",
#     )
#     month = forms.DateField(
#         required=False, widget=MonthYearWidget(years=xrange(2020, 2030))
#     )


class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = "__all__"

project1/blackbelt/views.py
from django.views import View
from django.views.generic.edit import FormView, CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.views.generic import TemplateView
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model, authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import LoginForm, PresenceForm, StudentForm
from .models import Group, Student, PresenceList
from extra_views import (
    CreateWithInlinesView,
    UpdateWithInlinesView,
    InlineFormSetFactory,
)
from django.core.mail import send_mail


class LoginView(View):
    def get(self, request):
        form = LoginForm()
        return render(request, "base.html", {"form": form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            # user = authenticate(**form.cleaned_data)

            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect("main")
        return render(request, "base.html", {"form": form})


class LogoutView(View):
    def get(self, request):
        if request.user.is_authenticated:
            logout(request)
            return redirect("login")


class MainView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, "main.html")


class GroupAddView(LoginRequiredMixin, CreateView):
    template_name = "group_add_form.html"
    model = Group
    fields = "__all__"
    success_url = reverse_lazy("groups")


class GroupsView(LoginRequiredMixin, View):
    def get(self, request):
        groups = Group.objects.all()
        return render(request, "groups.html", {"groups": groups})


class StudentAddView(LoginRequiredMixin, CreateView):
    template_name = "student_add_form.html"
    model = Student
    fields = "__all__"
    success_url = reverse_lazy("students")


class StudentsView(LoginRequiredMixin, View):
    def get(self, request):
        students = Student.objects.all()
        return render(request, "students.html", {"students": students})


class StudentDetailsView(LoginRequiredMixin, View):
    def get(self, request, student_id):
        student = Student.objects.get(pk=student_id)
        return render(request, "student_details.html", {"student": student})


class StudentEditView(LoginRequiredMixin, UpdateView):
    model = Student
    fields = "__all__"
    template_name = "student_edit_form.html"
    success_url = reverse_lazy("students")


class StudentDeleteView(DeleteView):
    model = Student
    success_url = reverse_lazy("students")


# class StudentEditView(LoginRequiredMixin, UpdateView):
#     # def get(self, request, student_id):
#     #     student = Student.objects.get(pk=student_id)
#     #     form = BeltForm()
#     model = Student
#     fields = "__all__"
#     template_name = "student_edit_form.html"
#     success_url = reverse_lazy("students")
# class BeltInline(InlineFormSetFactory):
#     model = StudentBelt
#     fields = ["belt"]


# class StudentEditView(LoginRequiredMixin, UpdateWithInlinesView):
#     model = Student
#     inlines = [BeltInline]
#     fields = "__all__"
#     template_name = "student_edit_form.html"

# #     success_url = reverse_lazy("students")
# class StudentEditView(LoginRequiredMixin, TemplateView):
#     student_form = StudentForm(instance=p)
#     belt_form = BeltForm(instance=p)
#     template_name = "student_edit_form.html"


class GroupEditView(LoginRequiredMixin, UpdateView):
    model = Group
    fields = "__all__"
    template_name = "group_edit_form.html"
    success_url = reverse_lazy("groups")


class GroupDetailsView(LoginRequiredMixin, View):
    def get(self, request, group_id):
        group = Group.objects.get(pk=group_id)
        students = group.student_set.all()
        return render(
            request, "group_details.html", {"group": group, "students": students}
        )


class GroupDeleteView(DeleteView):
    model = Group
    success_url = reverse_lazy("groups")


class PresenceView(LoginRequiredMixin, View):
    def get(self, request):
        form = PresenceForm()
        return render(request, "presence.html", {"form": form})

    def post(self, request):
        form = PresenceForm(request.POST)
        if form.is_valid():
            # student = form.cleaned_data["student"]
            # day = form.cleaned_data["day"]
            # print(student, day)
            PresenceList.objects.create(**form.cleaned_data)
            return redirect("main")
        else:
            return redirect("presence")


class SendMailView(LoginRequiredMixin, View):
    def get(self, request):
        form = EmailForm()
        return render(request, "send_email.html", {"form": form})

project1/blackbelt/templates/base.html
{% load static %}

<!doctype html>
<html>
    <head><meta charset="utf-8">
    <title>login</title>
    </head>
    
    <body>
    <div style="text-align:center">  
    <img  src="{% static 'bb.png' %}" alt="logo" width=300 /> 
    </div>
        <h1 style="text-align:center">Black Belt System</h1>
        <form action="{% url 'login' %}"method="POST">
            {% csrf_token %}
            <table style="margin-left:auto; margin-right:auto">
                {{ form }}
            </table>
            <div style="text-align:center">
            <input type="submit" value="Zaloguj" />
            </div>
        </form>
    </body>
</html>

project1/blackbelt/templates/group_add_form.html
{% extends "main.html" %}

{% block title %}group add{% endblock %}

{% block content %}
<p>DODAJ GRUPĘ:</p>
<form method="post">
    {% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="dodaj">
</form>
{% endblock %}

project1/blackbelt/templates/group_details.html
{% extends "main.html" %}

{% block title %}{{ group }}{% endblock %}

{% block content %}
<h1>{{ group }}</h1>
<p>Trener: {{ group.trainer }}</p>
<p>Uczniowie:</p>
<ul>
{% for student in students %}
<li>{{ student.name }}</li>
{% endfor %}
</ul>
<a href="/group_edit/{{ group.id }}"><button>Edytuj</button></a>
<a href="/group_delete/{{ group.id }}"><button>Usuń</button></a>
{% endblock %}

project1/blackbelt/templates/group_edit_form.html
{% extends "main.html" %}

{% block title %}group edit{% endblock %}

{% block content %}
<p>EDYTUJ GRUPĘ:</p>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="zapisz">
</form>
{% endblock %}

project1/blackbelt/templates/groups.html
{% extends "main.html" %}

{% block title %}groups{% endblock %}

{% comment %} {% block content %}
<h1>GRUPY:</h1>
<ul>
{% for group in groups %}
<li><a href="/group_details/{{ group.id }}">{{ group.name }}</a>, TRENER: {{ group.trainer }} <a href="/group_edit/{{ group.id }}">edytuj</a></li>
{% endfor %}
{% endblock %}
</ul> {% endcomment %}
{% block content %}
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
<table>
  <tr>
    <th>Grupa</th>
    <th>Trener</th>
    <th></th>
  </tr>
{% for group in groups %} 
  <tr>
    <td><a href="/group_details/{{ group.id }}">{{ group.name }}</a></td>
    <td>{{ group.trainer }}</td>
    <td><a href="/group_edit/{{ group.id }}">edytuj</a></td>
  </tr>
{% endfor %}
</table>
{% endblock %}

project1/blackbelt/templates/main.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>{% block title %}main{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: "Lato", sans-serif;
}

.sidenav {
  height: 100%;
  width: 160px;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #111;
  overflow-x: hidden;
  padding-top: 20px;
}

.sidenav a {
  padding: 6px 8px 6px 16px;
  text-decoration: none;
  font-size: 18px;
  color: #818181;
  display: block;
}

.sidenav a:hover {
  color: #f1f1f1;
}
.sidenav button:hover {
  color: #000000;
}

.main {
  margin-left: 160px; /* Same as the width of the sidenav */
  font-size: 18px; 
  padding: 0px 10px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
</style>
</head>
<body>

<div class="sidenav">
<a href="/main/">
<img  src="{% static 'bb.png' %}" alt="logo" width=150 /> 
</a>
  <a href="/groups/">Grupy</a>
  <a href="/students/">Uczniowie</a>
  <a href="/group_add/">Dodaj grupę</a>
  <a href="/student_add/">Dodaj ucznia</a>
  <a href="/presence/">Obecności</a>
  <a href="/payments/">Opłaty</a>
  <a href="{% url 'logout' %}"><button>Wyloguj</button></a>
</div>

<div class="main">
<h1 style="text-align:center">Black Belt System</h1>
{% block content %}
{% endblock %}
</div>  

</body>
</html> 

project1/blackbelt/templates/presence.html
{% extends "main.html" %}
{% block title %}presence{% endblock %}

{% block content %}
<h3>Dodaj obecność:</h3  >

<form action="{% url 'presence' %}" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Zapisz" />
</form>
{% endblock %}

project1/blackbelt/templates/student_add_form.html
{% extends "main.html" %}

{% block title %}student add{% endblock %}

{% block content %}
<p>DODAJ UCZNIA:</p>
<form method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="dodaj">
</form>
{% endblock %}

project1/blackbelt/templates/student_details.html
{% extends "main.html" %}

{% block title %}{{ student.name }}{% endblock %}

{% block content %}
<h1>{{ student.name }}</h1>
<p>Telefon: {{ student.phone }}</p>
<p>email: {{ student.email }}</p>
<p>Grupa: {% for group in student.groups.all %} {{group}} {% endfor %}</p>
<p>Pas: {{ student.get_belt_display }}</p>
<p>Notatki: {{ student.notes }}</p>
<p>Opłaty:</p>
<p>Obecności:{% for data in student.presencelist_set.all %} {{ data.day }};{% endfor %}</p>
<a href="/student_edit/{{ student.id }}"><button>Edytuj</button></a>
<a href="/student_delete/{{ student.id }}"><button>Usuń</button></a>
{% endblock %}

project1/blackbelt/templates/student_edit_form.html
{% extends "main.html" %}

{% block title %}student edit{% endblock %}

{% block content %}
<p>EDYTUJ UCZNIA:</p>

<form method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    {% for formset in inlines %}
    {{ formset.as_p }}
    {% endfor %}
    </table>
    <input type="submit" value="zapisz">
</form>

{% endblock %}

project1/blackbelt/templates/students.html
{% extends "main.html" %}

{% block title %}students{% endblock %}
{% block content %}
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
<table>
  <tr>
    <th>Uczeń</th>
    <th>Grupa</th>
    <th></th>
  </tr>
{% for student in students %} 
  <tr>
    <td><a href="/student_details/{{ student.id }}">{{ student.name }}</a></td>
    <td>{% for group in student.groups.all %} {{group}} {% endfor %}</td>
    <td><a href="/student_edit/{{ student.id }}">edytuj</a></td>
  </tr>
{% endfor %}
</table>
{% endblock %}